[package]
name = "destiny2-pkg"
version = "0.1.0"
edition = "2021"
authors = ["Lucas Cohaereo <cohaereo@protonmail.com>"]

[dependencies]
anyhow = "1"
aes = "0.8"
aes-gcm = "0.10"
binrw = "0.11"
lazy_static = "1.4.0"
libloading = "0.8"
nohash-hasher = "0.2.0"
