[package]
name = "destiny-pkg"
version = "0.3.0"
edition = "2021"
authors = ["Lucas Cohaereo <cohaereo@protonmail.com>"]

[dependencies]
anyhow = "1"
aes = "0.8"
aes-gcm = "0.10"
binrw = "0.11"
lazy_static = "1.4.0"
nohash-hasher = "0.2.0"
rayon = "1.7.0"
clap = { version = "4.3.11", features = ["derive"] }
clap-num = "1.0.2"
tracing = "0.1.37"
libloading = "0.8.0"

[package.metadata.appimage]
auto_link = true
assets = ["liblinoodle.so"]

[profile.release]
opt-level = 3
strip = "symbols"
lto = "fat"
