[package]
name = "destiny-pkg"
version = "0.8.0"
edition = "2021"
authors = ["Lucas Cohaereo <cohaereo@protonmail.com>"]

[dependencies]
anyhow = "1"
aes = "0.8"
aes-gcm = "0.10"
binrw = "0.12"
lazy_static = "1.4.0"
rayon = "1.7.0"
clap = { version = "4.3.11", features = ["derive"] }
clap-num = "1.0.2"
tracing = { version = "0.1.37", features = ["log"] }
libloading = "0.8.0"
json = "0.12.4"
ddsfile = "0.5.1"
parking_lot = "0.12.1"
serde = { version = "1.0.188", features = ["derive"] }
itertools = "0.12.1"
serde_json = "1.0.108"
rustc-hash = "1.1.0"

[features]
ignore_package_cache = []

[dev-dependencies]
env_logger = "0.10.0"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
tracing-tracy = "0.10.4"
tracy-client = "0.16.4"

[package.metadata.appimage]
auto_link = true
assets = ["liblinoodle.so"]

[profile.release]
opt-level = 3
strip = "symbols"
lto = "fat"

[profile.dev.package.aes]
opt-level = 3

[profile.dev.package.aes-gcm]
opt-level = 3
